name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  check-tag:
    runs-on: ubuntu-latest
    outputs:
      current_tag: ${{ steps.get-diff-result.outputs.current_tag }}
      code-server-version: ${{ steps.get-diff-result.outputs.code_version }}
      is-different: ${{ steps.get-diff-result.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - uses: oprypin/find-latest-tag@v1.1.0
        id: get-tag
        with:
          repository: ebrianne/docker-code-server

      - name: Check tags
        id: get-diff-result
        run: |
          set -e
          set -o pipefail

          TAG=${{ steps.get-tag.outputs.tag }}
          echo "::set-output name=current_tag::${TAG}"

          CODE_RELEASE=$(curl -sX GET "https://api.github.com/repos/cdr/code-server/releases/latest" | tac | tac | awk '/tag_name/{print $4;exit}' FS='[""]')
          echo "::set-output name=code_version::${CODE_RELEASE}"

          RESULT=false
          if [ "${TAG}" != "${CODE_RELEASE}" ]; then
              RESULT=true
          fi
          echo "::set-output name=result::${RESULT}"

      - name: Display tags
        run: |
          echo "Current tag is ${{ steps.get-diff-result.outputs.current_tag }}"
          echo "Current code-server tag is ${{ steps.get-diff-result.outputs.code_version }}"

  build-docker:
    runs-on: ubuntu-latest 
    needs: check-tag
    if: ${{ needs.check-tag.outputs.is-different == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          build-args: CODE_RELEASE=${{ needs.check_tag.outputs.code-server-version }}
          tags: ebrianne/code-server:${{ needs.check_tag.outputs.code-server-version }}

      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ needs.check_tag.outputs.code-server-version }}"